<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="7" total="8" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13061" started-at="2023-02-10T05:53:50Z" finished-at="2023-02-10T05:54:03Z">
    <groups>
    </groups>
    <test name="FirstTest" duration-ms="13061" started-at="2023-02-10T05:53:50Z" finished-at="2023-02-10T05:54:03Z">
      <class name="testClasses.StandAloneTest">
        <test-method status="PASS" signature="intialSetup()[pri:0, instance:testClasses.StandAloneTest@611889f4]" name="intialSetup" is-config="true" duration-ms="9405" started-at="2023-02-10T05:53:50Z" finished-at="2023-02-10T05:54:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialSetup -->
        <test-method status="FAIL" signature="userLogin()[pri:2, instance:testClasses.StandAloneTest@611889f4]" name="userLogin" duration-ms="2878" started-at="2023-02-10T05:54:00Z" finished-at="2023-02-10T05:54:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at pages.LoginPage.login(LoginPage.java:61)
at testClasses.StandAloneTest.userLogin(StandAloneTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userLogin -->
        <test-method status="PASS" signature="clearBrowser()[pri:0, instance:testClasses.StandAloneTest@611889f4]" name="clearBrowser" is-config="true" duration-ms="214" started-at="2023-02-10T05:54:03Z" finished-at="2023-02-10T05:54:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearBrowser -->
      </class> <!-- testClasses.StandAloneTest -->
    </test> <!-- FirstTest -->
  </suite> <!-- Suite -->
</testng-results>
