<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USBLRGRAVEE1" ignored="7" name="FirstTest" tests="1" failures="1" timestamp="10 Feb 2023 05:54:03 GMT" time="13.061" errors="0">
  <testcase name="userLogin" time="2.878" classname="testClasses.StandAloneTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pages.LoginPage.login(LoginPage.java:61)
at testClasses.StandAloneTest.userLogin(StandAloneTest.java:30)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- userLogin -->
  <testcase name="updateProfile" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- updateProfile -->
  <testcase name="transferFunds" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- transferFunds -->
  <testcase name="requestLoan" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- requestLoan -->
  <testcase name="payBill" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- payBill -->
  <testcase name="createNewUser" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- createNewUser -->
  <testcase name="openSavingsAccount" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- openSavingsAccount -->
  <testcase name="logOut" time="0.0" classname="testClasses.StandAloneTest">
    <ignored/>
  </testcase> <!-- logOut -->
</testsuite> <!-- FirstTest -->
