{"uuid": "f6a73da6-49aa-489c-ba0d-064c10152b62", "children": ["03efea20-0ee2-48dc-8328-2969bcec1a7f", "02f12862-a039-4c0f-a98b-c58dddb296a6", "867f529f-1794-41b4-aefa-89869b41314e", "e885d89b-dfe3-438c-891e-8df99407be1b", "6fae8875-7594-4804-bc98-a89eb67f7964", "9f1dd64b-ac34-468b-8362-deed7c3b1b6a", "6f2edb23-1216-4f88-8fa1-b1ac066319de", "dcf9be58-0a93-40ca-a989-89347c497c82", "d26129bb-d698-47c4-bc11-3a14d7263960", "fe45c361-3eae-4d23-9e35-d7cc47b64c21", "32e72431-c0a0-4a07-912c-4cb867ed4982", "8af80e9e-a9be-4e4f-9935-828ec0eebda2", "156e7fa0-1860-4815-a037-d46842dc2a8c"], "befores": [{"name": "setup", "status": "passed", "start": 1678426691639, "stop": 1678426700436}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=110.0.5481.178)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x010B37D3]\n\t(No symbol) [0x01048B81]\n\t(No symbol) [0x00F4B36D]\n\t(No symbol) [0x00F3BE5A]\n\t(No symbol) [0x00F3C63A]\n\t(No symbol) [0x00F3C5D8]\n\t(No symbol) [0x00F2D0BA]\n\t(No symbol) [0x00F2DBA7]\n\t(No symbol) [0x00FA489B]\n\t(No symbol) [0x00F9B3E3]\n\t(No symbol) [0x00F70D97]\n\t(No symbol) [0x00F7253D]\n\tGetHandleVerifier [0x0132ABF2+2510930]\n\tGetHandleVerifier [0x01358EC1+2700065]\n\tGetHandleVerifier [0x0135C86C+2714828]\n\tGetHandleVerifier [0x01163480+645344]\n\t(No symbol) [0x01050FD2]\n\t(No symbol) [0x01056C68]\n\t(No symbol) [0x01056D4B]\n\t(No symbol) [0x01060D6B]\n\tBaseThreadInitThunk [0x75B300F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x76FA7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x76FA7B8E+238]\n\n", "trace": "  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\tests\\conftest.py\", line 34, in setup\n    driver.close()\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678426712939, "stop": 1678426712941}], "start": 1678426691639, "stop": 1678426712941}